name: orcas
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - wxpython=4.1.1
  - numpy=1.20.0
  - scikit-video=1.1.11
  - ffmpeg  # ffmpeg version will be resolved automatically by conda-forge
  - opencv=4.5.0
  - pandas=1.3.3
  - matplotlib=3.4.3